// create a PROJECT
export const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';

// export type ProjectInfo = {
//   title: string,

// }

// update a PROJECT
export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';

// delete a PROJECT
export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';

// fetch all current user prjects
export const USER_PROJECTS_REQUEST = 'USER_PROJECTS_REQUEST';
export const USER_PROJECTS_SUCCESS = 'USER_PROJECTS_SUCCESS';
export const USER_PROJECTS_FAIL = 'USER_PROJECTS_FAIL';

// fetch all current user assigned projects: ASSIGNED_PROJECTS_REQUEST
export const ASSIGNED_PROJECTS_REQUEST = 'ASSIGNED_PROJECTS_REQUEST';
export const ASSIGNED_PROJECTS_SUCCESS = 'ASSIGNED_PROJECTS_SUCCESS';
export const ASSIGNED_PROJECTS_FAIL = 'ASSIGNED_PROJECTS_FAIL';

// single project for assigner
export const ASSIGNER_SINGLE_PROJECT_REQUEST = 'ASSIGNER_SINGLE_PROJECT_REQUEST';
export const ASSIGNER_SINGLE_PROJECT_SUCCESS = 'ASSIGNER_SINGLE_PROJECT_SUCCESS';
export const ASSIGNER_SINGLE_PROJECT_FAIL = 'ASSIGNER_SINGLE_PROJECT_FAIL';

// single project for assignee
export const ASSIGNEE_SINGLE_PROJECT_REQUEST = 'ASSIGNEE_SINGLE_PROJECT_REQUEST';
export const ASSIGNEE_SINGLE_PROJECT_SUCCESS = 'ASSIGNEE_SINGLE_PROJECT_SUCCESS';
export const ASSIGNEE_SINGLE_PROJECT_FAIL = 'ASSIGNEE_SINGLE_PROJECT_FAIL';